name: 'NPM Configure and Publish'
description: 'Configures NPM with the provided auth token, and optionally the provided registry url, then publishes packages.'
inputs:
  # packages-config-file:
  #   description: "The location of a json file that contains a `packages` property indicating the directories that will be published."
  #   required: true
  npm-auth-token:
    description: "Auth token that will be set for the provided registry using npm config."
    required: true
  npm-registry:
    description: "The url of the npm registry to publish to. This defaults to 'registry.npmjs.org'."
    required: false
    default: "registry.npmjs.org"
  dry-run:
    description: "Runs this action replacing actual publishes and tagging with logging."
    required: false
    default: "false"
runs:
  using: 'node12'
  main: 'dist/index.js'
