name: Branch

on: [push]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo a secret"
        env:
          test-secret: ${{ secrets.TEST_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: 'echo "$test-secret"'
