name: Branch

on: [push, pull_request]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo a secret"
        env:
          testsecret: ${{ secrets.TEST_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$TEST_SECRET" && echo "$testsecret"
